### ISSUE TITLE
CVS Scraper Offline?

### ISSUE THREAD

**Issue by iann** [livgust/covid-vaccine-scrapers#107]
While doing some data analysis of appointment availability I found that since 2/13 until now the CVS scraper has not found availability. I find this odd since I know first hand two people who were able to get appointments at CVS via their website, this leads me to believe that the scraper is not functioning as intended.

Additionally going to https://www.cvs.com/immunizations/covid-19-vaccine.vaccine-status.ma.json?vaccineinfo I get an Access Denied.

**Comment by johnhawkinson** [comment]
CVS needs the Referer:  [sic] header to work. I use

```
wget --referer=https://www.cvs.com/immunizations/covid-19-vaccine https://www.cvs.com/immunizations/covid-19-vaccine.vaccine-status.ma.json
```

and it looks to me like the scraper is properly retrieving and returning the right file.
That doesn't mean it isn't lying, though.

**Comment by iann** [comment]
Doh! That pulls up the JSON. Still not sure why it's never seen availability. Hmm.

**Comment by iann** [comment]
Closing this. This is more of an issue with my computer not properly able to handle all the data I'm searching.
