### ISSUE TITLE
A data quality mechanism to detect unbookable appointments

### ISSUE THREAD

**Issue by johnhawkinson** [livgust/covid-vaccine-scrapers#113]
We saw last night in #110, scrapers can discover availability that is not publicly available and publicly bookable.
No matter how good our scrapers are[*], this will continue to happen.

Therefore, we should attempt to detect this.
(This probably requires a database server or other intermediate layer between the scrapers and the front end).

Ideally, we would notice when a large number of appointments are newly available (e.g. _N > 30_) and monitor it for a period of time (_t > 10 minutes_) and if _N_ does not decrement at all, assume that the new appointments are not available and either flag them for human review or remove them from public display on our website (or both!) (perhaps via heuristic).

This is not a good fit architecturally right this moment.

----
[*] We have two kinds of scrapers:
**Type I:** Those that start from a clear customer-facing URL and follow the interactions that a user would do.
**Type II:** Those that jump in _in media res_ with a URL we've learned from introspection of a normal interaction and used that knowledge to shortcircuit some steps.

Type I scrapers are much less likely to have this problem.

(It is, however, not clear that Type I scrapers are more generally robust. They are more vulnerable to small website tweaks that can break scrapers. The question may be whether we'd prefer those tweaks to break the scrapers and avoid showing potentially bad data, or to keep the scraper running and perhaps show data that may not be intended for the public.)

**Comment by livgust** [comment]
Things have stabilized now, so closing as a won't-do. Reopen if you disagree and want to do it!
