### ISSUE TITLE
Deploy repo continuously

### ISSUE THREAD

**Issue by tkjones117** [livgust/covid-vaccine-scrapers#117]
The frontend repo automatically deploys on merging to master (handled by AWS Amplify).

Making this repo deploy continuously will require: 
- zip up the file (already have an npm command for that) 
- then upload to S3
- link to Lambda
- publish new version
- (ideally do a test run)
- then update the production alias

^ I grabbed these high-level steps from [a Slack thread](https://macovidvaccines.slack.com/archives/C01NADTMYQM/p1614866428053200?thread_ts=1614861151.039000&cid=C01NADTMYQM))

**Comment by tkjones117** [comment]
@livgust Work has been started on this by @j256: https://github.com/livgust/covid-vaccine-scrapers/pull/121

Assigning this to @j256 for now.

**Comment by tkjones117** [comment]
@kriation I saw you have a PR (https://github.com/livgust/covid-vaccine-scrapers/pull/148) up that looks similar to this issue: 
Maybe you can @j256 can sync up (on this ticket is fine) to make sure there isn't duplicative work, or perhaps @j256 wants to hand it off (in which case can you reassign to the right person) or pair/provide feedback.

**Comment by j256** [comment]
I think my work can be ignored, especially if someone else has taken it on.  If there is anything there of value please feel free to steal it.  I've been pulled away on another of my projects.  But I'm also happy to help if people hit a stumbling block.

**Comment by livgust** [comment]
yeah, sorry - I assumed that since @kriation commented on @j256 's initial PR that he was just building off of that. I'll assign this issue to him and we'll use #148 as the main PR for this issue.

**Comment by kriation** [comment]
Can this be closed given @livgust completed #162?
