### ISSUE TITLE
Add Harvard Vanguard

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#14]
EASY for yes/no appt availability. If no appointments available, redirects to https://myhealth.atriushealth.org/fr/No_Slots.asp

**Comment by adpjay** [comment]
I'm working on this one and will have a PR later today.
The following 3 requests need to be made:
https://myhealth.atriushealth.org/fr/
https://myhealth.atriushealth.org/DPH
https://myhealth.atriushealth.org/OpenScheduling/OpenScheduling/GetScheduleDays

And the __RequestVerificationToken hidden input field needs to be pulled out of the DPH request and added as a header to the GetScheduleDays POST with data 'view=grouped&specList=121&vtList=1424&start=&filters=%7B%22Providers%22%3A%7B%7D%2C%22Departments%22%3A%7B%7D%2C%22DaysOfWeek%22%3A%7B%7D%2C%22TimesOfDay%22%3A%22both%22%7D'
