### ISSUE TITLE
Add Trinity Health of New England

### ISSUE THREAD

**Issue by harcod** [livgust/covid-vaccine-scrapers#164]
https://apps.sphp.com/THofNECOVIDVaccinations/index.php

**Comment by pfurbacher** [comment]
Is anyone working on this? If not, I'll give it a go.

**Comment by harcod** [comment]
You are correct! This is just a different name for the same place.

![image](https://user-images.githubusercontent.com/546007/113195189-f8c96b00-922f-11eb-802e-62b537733fe8.png)
