### ISSUE TITLE
Add Baystate Health

### ISSUE THREAD

**Issue by harcod** [livgust/covid-vaccine-scrapers#168]
https://workwell.apps.baystatehealth.org/guest/covid-vaccine/register?r=mafirstresp210121

**Comment by kriation** [comment]
@harcod Is this a duplicate of #11? The closed PR is #102.

**Comment by harcod** [comment]
I got the url from @livgust

**Comment by kriation** [comment]
@harcod - Yep. That's the [link](https://github.com/livgust/covid-vaccine-scrapers/pull/102/files#diff-03ffc9e6023468d2a06c339dad2e153949362b8aa6be81204ff1666e5ff4ab8eR399) I used in the scraper.
