### ISSUE TITLE
Add Amherst Clinic

### ISSUE THREAD

**Issue by harcod** [livgust/covid-vaccine-scrapers#170]
https://www.amherstcovid19.org/vaccine

**Comment by relm923** [comment]
Looks like this has been replaced with https://uma.force.com/covidtesting/s/vaccination

**Comment by pfurbacher** [comment]
How important is it to get this scraper going? The only changes I would make are to update the `config.js` file with the new URL, and maybe add an s3/slackMsg block in case the "No appointments available" comment isn't found.

**Comment by harcod** [comment]
@livgust These are actually separate. I think this can probably be closed now.

https://uma.force.com/covidtesting/s/vaccination is done already. (UMassAmherst)

The original link was added to the mass vaccination sites and subject to preregistration via https://vaccinesignup.mass.gov

**Comment by harcod** [comment]
Based on the above, I'm closing this issue.
