### ISSUE TITLE
Add PriceChopper

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#19]
EASY. PriceChopper has public API https://scrcxp.pdhi.com/ScreeningEvent/e047c75c-a431-41a8-8383-81613f39dd55/GetLocations/01201?state=MA, where 01201 is the zip

**Comment by zpeyton** [comment]
JSON response is great but when replacing the zip with other zip codes I get an empty array. Might need a different event hash ("e047c75c-a431-41a8-8383-81613f39dd55") for different locations.
