### ISSUE TITLE
Initialize scraper for Wegmans

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#21]
HARD to determine if appts are available.

**Comment by aaminoff** [comment]
I am considering trying to take this one on. I can copy UMassAmherst.js and look for the phrase "All available vaccine* appointments are reserved at this time." on https://www.wegmans.com/pharmacy/ , but that is for all Wegmans in all states. Also, Wegmans has 4 sites in MA. I would not want to claim there were appointments available when the appointments are in New Jersey or only at one of the 4 sites. So would it be best to wait until there are at least some openings available and then try to build the scraper?

**Comment by aaminoff** [comment]
I submitted a contact form reaching out to them.

**Comment by aaminoff** [comment]
Dear Alex,

Thank you for contacting us requesting to partner with Wegmans to assist in scheduling COVID-19 vaccine appointments that are available by accessing our system.

Your request has been forwarded to our Pharmacy team for review.

We want to thank you for giving us the opportunity to respond to your request.

Have a good day.


Sincerely,

Kim Ayles
Customer Care Specialist

Ref # 2271353
