### ISSUE TITLE
Add scraper hierarchy

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#214]
Some scrapers dynamically generate locations based on what is pulled from the website. Most of these websites do not show locations if there is no availability, in which case we act as if there is no updated data (and show stale availability) instead of saying there's nothing available.

To solve this issue, we add parentLocations and parentScraperRuns to our DB. There will be one parentLocation per scraper/website, and for each run of the scraper we add a row to parentScraperRuns. This signals that we have successfully scraped all location data from the website and that anything _not_ included means that there is no availability.

**Comment by livgust** [comment]
branch: `add-parent-rows`

**Comment by harcod** [comment]
Walgreens is the prime example of this problem.
