### ISSUE TITLE
Add scraper for Greater Lawrence Family Health Center

### ISSUE THREAD

**Issue by pfurbacher** [livgust/covid-vaccine-scrapers#228]
The Greater Lawrence FHC has 4 locations where they offer vaccinations, each of which has its own availability page. The site is powered by Acuity Scheduling (see Trinity EMS and Harrington). Even though it might be tempting to consolidate all Acuity sites into one scraper, I propose we add a scraper specifically for GL FHC: faster to write, test and deploy. One of the locations has been showing a lot of availability today. 

I do have a working scraper, and accompanying test.

**Comment by livgust** [comment]
Hey @pfurbacher thanks so much! Do you have something ready for a PR or not yet?

**Comment by pfurbacher** [comment]
Yes, I was waiting for a confirmation that we should add these 4 sites. Doing the PR now.
