### ISSUE TITLE
Fix Hannaford

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#24]
Hannaford's scraper tends to be flaky; we should investigate and also add functionality (if possible) to figure out what sites have how much availability. I wasn't able to do that in a first pass because none of the locations had availability so I didn't know what the display looked like.

**Comment by zpeyton** [comment]
I finally got an open appointment! Will start on this. May require playing around with opening a new browser or deleting cookies as I got the following response when sending too many requests within a short amount of time:

![Screen Shot 2021-02-12 at 10 43 30 PM](https://user-images.githubusercontent.com/1585834/107855541-ec5c9080-6df0-11eb-8959-3dc2f3ea3976.png)

Also found this as a possible solution: https://stackoverflow.com/questions/55871650/how-to-clear-history-clear-browsing-data-in-node-js-puppeteer-headless-false-c

**Comment by zpeyton** [comment]
Almost forgot. I wanted to add a follow up comment regarding the possible cookie issues here. When trying multiple zip codes doing a `page.goto(sites.Hannaford.website);` seems to reset their number of tries without clearing cookies. I've run the script multiple times without getting locked out.

**Comment by tkjones117** [comment]
@zpeyton see my issue and cookie deletion fix here for Stop & Shop: https://github.com/livgust/covid-vaccine-scrapers/pull/51 

I haven't seen any appointment availability come up yet for Stop & Shop.

**Comment by tkjones117** [comment]
@livgust do you recall in which way the Hannaford scraper was flaky?

**Comment by tkjones117** [comment]
@zpeyton Can we close this in favor of https://github.com/livgust/covid-vaccine-scrapers/issues/84?

**Comment by zpeyton** [comment]
@tkjones117 Indeed, thanks for making the new issue.
