### ISSUE TITLE
Zipcode for Hannaford Middleborough should be 02346

### ISSUE THREAD

**Issue by pfurbacher** [livgust/covid-vaccine-scrapers#27]
Currently, in ```sites.json``` the zip code for the Middleborough store is "01569".

According to a usps.com zip code search, the correct zip code is "02346".

(Looks like a copy-paste error from the Uxbridge data.)

**Comment by zpeyton** [comment]
This has been fixed in the zach-test branch.

**Comment by livgust** [comment]
Re-opening and assigning to @zpeyton until his branch is merged. In the future, @zpeyton, if you branch off this repo (vs forking) could you make branch names more descriptive? Thanks!

**Comment by zpeyton** [comment]
No prob. That branch was literally just a test. I have made a new branch called Add-PriceChopper which has those changes including this fix: https://github.com/livgust/covid-vaccine-scrapers/pull/30
