### ISSUE TITLE
Idempotency Concern of the MACovidVaccineAlerts Function

### ISSUE THREAD

**Issue by NullPointer4096** [livgust/covid-vaccine-scrapers#293]
I would like to kindly bring your attention to a potential issue in the [MACovidVaccineAlerts](https://github.com/livgust/covid-vaccine-scrapers/blob/d1f3039d97ee41725d2edbde11a0847dca4db89c/alerts/index.js#L701) function, which is invoked by [MACovidVaccineScraper](https://github.com/livgust/covid-vaccine-scrapers/blob/d1f3039d97ee41725d2edbde11a0847dca4db89c/template.yaml#L68) and [MACovidVaccineNoBrowserScraper](https://github.com/livgust/covid-vaccine-scrapers/blob/d1f3039d97ee41725d2edbde11a0847dca4db89c/template.yaml#L102). In the [handleIndividualAlert](https://github.com/livgust/covid-vaccine-scrapers/blob/d1f3039d97ee41725d2edbde11a0847dca4db89c/alerts/index.js#L617) method of MACovidVaccineAlerts, if the program finds available vaccine appointments at a location and no mass alert has been sent according to the internal database ([massAlertAlreadySent](https://github.com/livgust/covid-vaccine-scrapers/blob/d1f3039d97ee41725d2edbde11a0847dca4db89c/alerts/index.js#L639)), it marks the alerts to be sent in the database ([setMassAlert](https://github.com/livgust/covid-vaccine-scrapers/blob/d1f3039d97ee41725d2edbde11a0847dca4db89c/alerts/index.js#L642)) and then sends the alert through Slack and Twitter ([runAlerts](https://github.com/livgust/covid-vaccine-scrapers/blob/d1f3039d97ee41725d2edbde11a0847dca4db89c/alerts/index.js#L643)). However, this multi-step workflow is not idempotent. Suppose the function runtime crashes after checkpointing in the database but right before actually calling lambdas to send the alerts; when the function retries, it will find the alerts marked as sent, so no further alerts will be sent. Unfortunately, even the next scraper run that finds available appointments could not trigger any alert sending; until the spots are filled and opened again for a location, the alerts could then be sent.

Achieving idempotency for this notification workflow is challenging and perhaps nearly impossible. Currently, the workflow guarantees at-most-once notification, given that the runtime could fail after marking the checkpoint in the database but before sending anything. If we adjust the order of the steps – making the sending happen first and then checkpointing in the database – we could provide an at-least-once notification. Additionally, Twitter would automatically block repeated tweets over a short period of time, and for Slack message sending, if the program uses Slack API to query the channel’s recent message to determine whether such an alert has already been sent, and only sends if this alert has been found, we could achieve exactly-once notification.

Thank you for considering this potential issue. I hope that this analysis can help identify potential areas of improvement for the MACovidVaccineAlerts function. Please feel free to reach out if you have any questions or concerns.

**Comment by livgust** [comment]
Hi! Thanks for taking a look through the codebase. This service is no longer in use, since about 2 years ago, so I will be closing the issue.
