### ISSUE TITLE
Add Twitter notifications for new vaccine availability

### ISSUE THREAD

**Issue by johnhawkinson** [livgust/covid-vaccine-scrapers#32]
Cribbing this idea from NY's https://twitter.com/turbovax, we should provide asynchronous notifications of new vaccine availability, so people can subscribe and find out when there are new sites available.

(This will be much more important when the floodgates open to new Priority Groups).

Twitter is an easy way to do this, and a more difficult one is allowing email signups.
Although the latter could be more targetted ("When is there a site near _my_ zipcode?") (some other sites do this).

We don't really have the architecture for this, but that's solvable (but there is some design thinking here).

(We recognize this Issue doesn't quite fit this repo. After discussion with @livgust we decided such miscellaneous items are best placed here, at least for now.)

**Comment by livgust** [comment]
Given that the bot @vaccinetime does this, I'm closing it. If we do work in this area it'll likely be email & text notifications I think. Certainly would be high-impact.
