### ISSUE TITLE
Separating scrapers

### ISSUE THREAD

**Issue by zpeyton** [livgust/covid-vaccine-scrapers#36]
Without getting into too many details, in my past scraping work we ran each site separately. I pushed a couple ways we could go about doing that below. Would be interested in any feedback from the group.

See options here: https://github.com/livgust/covid-vaccine-scrapers/compare/dynamic-scrapers

Usage would be:

ENV `SCRAPERS="PriceChopper Hannaford"`

or

`node main.js PriceChopper Hannaford`

**Comment by adpjay** [comment]
I like the separate argument approach. I've been commenting out the others from the index. 
It might be a good idea to add an argument parser if we want to add some more sophisticated arguments. But starting with the positional argument is a good start!

**Comment by zpeyton** [comment]
Indeed, commenting out does work but then you have to remember to discard those changes. I've experienced merge conflicts in those spots as well, 2 in that index file and 1 in `data/sites.json`.

Plus, there are also scaling issues if running all the sites at the same time. Right now there is only one log file so to find the brand you're looking to debug in that log you'd need to navigate a potentially huge file with many sites.

We also need to somehow merge availability data from sites we can't scrape so joining all the separate site data.json files is something we probably need to do anyway.

**Comment by adpjay** [comment]
I agree. Commenting it out and having to remember to uncomment is not preferred. Having the ability to select which site you want to run or test is much better. I like the separate command-line argument approach.

**Comment by aaminoff** [comment]
You can in fact do node main.js PriceChopper Hannaford . The functionality to read the cmd line args is in site-scrapers/index.js. So either someone added this functionality or it was there all along. Should we mark this issue as resolved?

**Comment by zpeyton** [comment]
@aaminoff thanks for the reminder, I was busy with #3 and #62. Just in case it is useful in the future, it is possible to determine who made changes by looking at the git log, or GitHub has a nice web based UI for seeing the blame. Ex: https://github.com/livgust/covid-vaccine-scrapers/blame/master/site-scrapers/index.js

I think the work being done in #55 covers some of the scaling issues that came to mind. It would also be nice to separate the failure logs to help with debugging.
