### ISSUE TITLE
BMC clinics

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#37]
There are 5 new locations that are giving our vaccines for residents. https://mychartscheduling.bmc.org/MyChartscheduling/covid19#/scheduling

**Comment by livgust** [comment]
WIP in branch `boston-medical-center`

**Comment by livgust** [comment]
If anyone is interested, I have a half-done scraper for BMC in the boston-medical-center branch. I finally nabbed a response with an actual available appointment. This is a MyChart scraper but needs some additional work because the one endpoint spans 5 locations, which are listed as "departments." So right now we just show general overall availability as if there were only one location.

TODO: Always return 5 results
TODO: Group availability by location by cross-referencing with Department information, which is also given in the response.

**Comment by Kathleen-Francis** [comment]
Can't assign this to myself, but I am starting to work on it!

**Comment by zpeyton** [comment]
@Kathleen-Francis assigned you after accidentally assigning myself. Shows how much of an ass I am.
