### ISSUE TITLE
Atrius Needham not showing correct numbers

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#38]
Hello Olivia-

I notice your website indicates no appointments available at Atrius 
in Needham, but their site shows multiple openings. 
Maybe there's a glitch in getting the info to cross.

https://myhealth.atriushealth.org/fr/

Thanks- 
I hope this task isn't wearing you down. You're providing a
wonderful service. 
Jon

---

Note from Olivia: We are reporting this:
![image](https://user-images.githubusercontent.com/8116945/108006981-d60a2c80-6fca-11eb-8881-a4d8e2887b5d.png)
but Atrius website says:
![image](https://user-images.githubusercontent.com/8116945/108006997-e15d5800-6fca-11eb-9769-9a0931635226.png)

Time: 8:17 PM. I'm a little nervous that there's a UTC date line issue going on here, among other things.

**Comment by adpjay** [comment]
I was just about to log a bug for a simliar problem:

The API shows this data:
![image](https://user-images.githubusercontent.com/6526064/108007552-44032380-6fcc-11eb-8281-6b7be6abebd2.png)
 
The UI shows this data:
![image](https://user-images.githubusercontent.com/6526064/108007579-55e4c680-6fcc-11eb-9ebf-61a726de4555.png)

This problem seems be be afflicting:
Atrius
Lynn Field House
Price Chopper
Southbridge Community Center


These vaccination sites are not affected:
Eastfield Mall

**Comment by livgust** [comment]
I'm not seeing that, @adpjay . I just checked and what I'm seeing our website get from the API endpoint matches what is being rendered. However, there is definitely a distinct difference between the official UI for Atrius availability and what we're scraping.

**Comment by adpjay** [comment]
I have a fix for the fact that we're not seeing the 2/23 date. It was my first site. I didn't realize we needed to loop over future weeks. I just a simple MyChart site, so I could just use the general mychart code.

If you look at the two images you added to the defect:
We are showing availabilities on 2/19 and 2/20, but Atrius is showing 2/18 and 2/19.
The image I added with the json data also shows 2/18 and 2/19.

There are a few other vaccination sites showing this same discrepancy. I think we should log a new bug.

**Comment by livgust** [comment]
Right; there's a day offset but it's happening on the scraping side, not the front-end side was my point. Good find re: subsequent weeks!

I really think this is a UTC thing. It's like 2 AM tomorrow UTC so we crossed the date line.

**Comment by livgust** [comment]
UGH yup
![image](https://user-images.githubusercontent.com/8116945/108011923-21760800-6fd6-11eb-818b-40e760cb55dc.png)
https://stackoverflow.com/questions/7556591/is-the-javascript-date-object-always-one-day-off

**Comment by adpjay** [comment]
So, do we need to change all the scrapers to return an east coast time stamp? Will the UI handle the full timestamp ok?

**Comment by livgust** [comment]
I think we can fix this by just adding "T00:00" to the end of the DateISO, which tells the Date object to stay in our timezone.
![image](https://user-images.githubusercontent.com/8116945/108082111-b7924880-703f-11eb-8767-5c11e03cdc6b.png)
I'll look and see if any other scrapers are using Date() but I think most we're just scraping the text to get MM/DD/YYYY so might not be a problem except for MyChart

**Comment by livgust** [comment]
I see two other places where we do date conversions like that; I'm going to review your PR and then make a fix to all 3 locations on a separate branch.

**Comment by livgust** [comment]
Going to fix this in a separate PR.

**Comment by adpjay** [comment]
There were two bugs here:
1. We weren't scraping future weeks from Atrius showing fewer appointments than there actually were.
2. The MyChart sites had a bug with the date being UTC and showing appointments for the wrong day.

Both of these problems are fixed.
