### ISSUE TITLE
Add South Boston Community Health Center

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#5]
Notes from spreadsheet:
EASY. MyChart. http://bit.ly/3t8A7AJ is actual link for availability. We'll want to use the link in the Website column as the sign-up link though. There's a request https://mychartos.ochin.org/mychart/OpenScheduling/OpenScheduling/GetOpeningsForProvider that returns JSON info on availability instead of needing to scrape HTML.

**Comment by tkjones117** [comment]
If I comment on this, will this let you assign to me? let's find out...
```
You can assign up to 10 people to each issue or pull request, including yourself, anyone who has commented on the issue or pull request, anyone with write permissions to the repository, and organization members with read permissions to the repository.
```
https://docs.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users

**Comment by tkjones117** [comment]
So I understand that eventually the item on the website will need to link to http://bit.ly/38SUWs2. 

But as far as getting actual availability, I'm not seeing any JSON info returned from https://mychartos.ochin.org/mychart/OpenScheduling/OpenScheduling/GetOpeningsForProvider - only getting a 404. 

Seems like I will need to scrape HTML instead in this case, starting from https://mychartos.ochin.org/mychart/OpenScheduling and choosing the right location/treatment and seeing what times are presented.

**Comment by tkjones117** [comment]
So I'll use Puppeteer to visit the site and catch this JSON response.

**Comment by tkjones117** [comment]
FYI - I'm mostly available to work during the work week, less so on the weekends/holidays. So I'll pick this up on Tuesday 2/15, unless someone else is very eager to. What I've posted is as far as I've gotten.

**Comment by tkjones117** [comment]
PR: https://github.com/livgust/covid-vaccine-scrapers/pull/41

**Comment by tkjones117** [comment]
Closing since this was completed in https://github.com/livgust/covid-vaccine-scrapers/pull/41.
