### ISSUE TITLE
Preserve previous scrape results in the event of a scraper failure

### ISSUE THREAD

**Issue by adpjay** [livgust/covid-vaccine-scrapers#55]
- Read the previous scrape result from the S3 data.json file.
- Run all the scrapers and collect the results. Add a timestamp to the result object indicating the updateTime.
- Create a new result from the scraper results. Any entries that failed to scrape will not be in the new scrape results
- Iterate over all the results from the previous data.json and add all missing scrape results with the old results, preserving the previous timeStamp.
- write the data.json and the timestamped data.json to s3.

**Comment by livgust** [comment]
Resolved by #52
