### ISSUE TITLE
Add Stop and Shop

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#6]
Notes from spreadsheet:
EASY FIRST PASS. Same system as Hannaford - when I can get to the actual scheduling page though (if there's a place with availability) it seems a little rough to scrape, but it would be easy to do a first pass and just tell if there are appointments available or not (just not how many).

**Comment by tkjones117** [comment]
PR: https://github.com/livgust/covid-vaccine-scrapers/pull/51

**Comment by kriation** [comment]
@tkjones117 (cc: @livgust), can this issue be closed since #51 is merged?
