### ISSUE TITLE
Add Walgreens (multiple sites)

### ISSUE THREAD

**Issue by aaminoff** [livgust/covid-vaccine-scrapers#65]
liv  9:41 AM
I have some code but it's not checked in. It works except Walgreens detects when I run headless and blocks me
9:41
So I've been pressuring them to make their API public (right now I have to log in to use it)

**Comment by aaminoff** [comment]
My neighbor Eric said he might be able to put us  in touch with folks in the IT dept at Walgreens. Not to raise hopes too much, it is a big company.

**Comment by livgust** [comment]
branch is `walgreens` for WIP
My aunt used to work at the tech side of Walgreens; she got me in contact with someone who said it was escalated to their IT dept to make that API public. Haven't heard since last Tuesday.
