### ISSUE TITLE
Natick Mall: shows 0 availability but still shows link and counts as available

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#68]
![image](https://user-images.githubusercontent.com/8116945/108614529-4e0c9400-73c9-11eb-8d98-edebba32e5a1.png)
For some reason the boolean props say that the location has availability but the number of slots available is zero. Assigning Jay since he created the scraper; anyone can grab if they beat him to it.

**Comment by adpjay** [comment]
I think I see what the problem is. Give me a few minutes.
