### ISSUE TITLE
Validate Data returned from the scrapers

### ISSUE THREAD

**Issue by harcod** [livgust/covid-vaccine-scrapers#79]
As the we are adding functionality (like geocoding or timestamping), it is becoming necessary to touch each individual scraper to add it.

We need to validate that the scrapers are returning the bare minimum required by the other modules (front-end, caching) so that new scrapers don't break the system.

For example:
Each location needs to have **hasAvailability** defined to either _true_ or _false_
Each location needs a timestamp for caching and front-end staleness checks.
Each location needs a **longitude** and **latitude**.

**Comment by livgust** [comment]
Hey @harcod , sorry to throw this on you but I've been working on something similar in a branch off of this project. `results-shape-test`
I have "no unexpected keys" passing, but haven't added lat & long yet. I was going to work on types, conditional keys, and other validity checks next. You can kinda see where I was going at the top of the main.js test file.

**Comment by harcod** [comment]
No problem. I'll just close my PR #80.
