### ISSUE TITLE
Add UMass Memorial HealthAlliance

### ISSUE THREAD

**Issue by livgust** [livgust/covid-vaccine-scrapers#8]
EASY. Another MyChart that goes straight to availability.

**Comment by tkjones117** [comment]
This should be easy enough, similar to https://github.com/livgust/covid-vaccine-scrapers/issues/5

I can pick this up tomorrow (Wed 2/17).

**Comment by Kathleen-Francis** [comment]
I'll start working on this one (I don't have access to assign to myself).

**Comment by tkjones117** [comment]
Assigned you Kathleen!
