### ISSUE TITLE
Scrape S&S and Hannaford appointments

### ISSUE THREAD

**Issue by tkjones117** [livgust/covid-vaccine-scrapers#84]
Currently we just scrape for availability = false, and upload a screenshot and HTML to S3 when we see actual appointments.

Let's reconstruct the API calls to actually grab the appointment data. 

I have the .har file on my laptop to retrace steps.

**Comment by zpeyton** [comment]
@tkjones117 Thanks again for starting fresh here. Looking forward to working with you on this.
