### ISSUE TITLE
MAImmunizations: Waiting Room

### ISSUE THREAD

**Issue by harcod** [livgust/covid-vaccine-scrapers#87]
MAImmunizations.org added a "waiting room" feature early on Thursday 2/25.

At the time of this issue the wait times are 5 minutes.  Our site hasn't scraped new data in the last 14 minutes.

**Comment by livgust** [comment]
@harcod any suggestions? I think this is starting to really show that we need to separate our scrapers out and let them run independently like others have suggested.
When the wait time is under ~3 minutes we can do a scrape currently

**Comment by harcod** [comment]
Now the state has given up and simply redirects everyone to a "No Appointments Found" page.  _At least this is hosted on AWS! with a lovely url_
https://cw2-errorpages.s3.us-east-2.amazonaws.com/no-appointments.html

I agree with separating the scrapers out as a superior architecture in general.

**Comment by harcod** [comment]
I escalated this to an issue this morning just so that everyone might see it.  Feel free to close this issue in favor of a more specific call-to-action set of issues.

**Comment by harcod** [comment]
This was essentially eliminated recently as the state moved the MassVax sites off of this site.
