### ISSUE TITLE
Preserve HTML/JSON/&c. from all scrapers

### ISSUE THREAD

**Issue by johnhawkinson** [livgust/covid-vaccine-scrapers#88]
As noted on Slack this morning:
> It does make me wonder if all scrapers should be saving all ~HTML~ **downloads** all the time so we can do useful forensic analysis.

there seemed to be broad support for this at this morning's standup.
@zpeyton noted that `Hannaford.js` already does something similar, by loading `s3.js` and invoking it as:

```
                if (!process.env.DEVELOPMENT) {
                    await s3.savePageContent(`${siteName}-${loc.zip}`, page);
```

This proposal is for something more automatic that happens for all downloads that all scrapers do, because it's hard to predict what we will need until it is no longer available.

My initial thinking was that this would be done with a Puppeteer hook ("intercepting"?), but that would also put this in Javascript async hell, so I am leaving this open but I don't intend to work on it because of that trail of tears.

Also, not all scrapers use Puppeteer. Some use the `node-fetch` and some use raw `https` (wrapped in Promises?) and there may be other APIs.

**Comment by livgust** [comment]
Closing - won't do - reopen if we feel strongly about this
