### ISSUE TITLE
Curative: "The event has ended"

### ISSUE THREAD

**Issue by harcod** [livgust/covid-vaccine-scrapers#96]
We are currently showing intermittent availability at Curative, however the sign up link redirects to "_The event has ended_"

https://curative.queue-it.net/afterevent.aspx?c=curative&e=curativemaprod2&t=https%3A%2F%2Fcurative.com%2Fsites%2F25336&cid=en-US

Can we change this scraper to report "no availability" in this redirection case?

**Comment by harcod** [comment]
A related case is when the redirection takes you to the curative.com site and it just says "No Appointment Times" (or something like that -- I don't have an example")

We were attempting to use the API flag `visible_in_search` but this appears to always be false and worthless to us.

**Comment by livgust** [comment]
Closing (wont-do) because Curative is now only for pre-registrants
