### ISSUE TITLE
Walgreens (Hyannis) showing incorrect availability

### ISSUE THREAD

**Issue by harcod** [livgust/covid-vaccine-scrapers#97]
The site is currently showing "1 slot" available at Walgreens (Hyannis).  However, we I run the scraper locally my result shows _no availability._

**Comment by livgust** [comment]
I just ran locally under the same credentials and I confirmed I am NOT seeing any availability for Hyannis.

Maybe someone could add some logging and I can publish that to Lambda?

**Comment by iann** [comment]
I took at a look at this last night. I added some timestamps in #91. However, the core of the issue is happening in the `mergeResults` when we merge with cached Data since the keys generated are slightly different (zip code has no leading zero). I'm not sure how this data made it into the cache.

**Comment by harcod** [comment]
Here's a quick fix to clean up the site data.
Why don't we just change the key that is generated?

in dataDefaulter.js, line 45:
`.replace(/[^\w]/g, "")`

to 
`.replace([^1-9bcdghj-np-tv-z]/g, "")`

This will remove all of the vowels and the '0' from the key.
**road**, **rd** match as _2631_
**02601**, **2631** match as _2631_

Then the merge code won't use the old bad data.

Here are the keys above:

> wlgrnshynns52wmnsthynns261
wlgrnshynns52wmnsthynns261

>wlgrnspttsld37chshrrdpttsld121
wlgrnspttsld37chshrrdpttsld121
